### ISSUE TITLE
出现了个bug fnc.js 里边的today好像不能随时间变化

### ISSUE THREAD

**Issue by waitforraining** [Jimmylxue/Vitality-reminder#1]
![image](https://user-images.githubusercontent.com/53138029/187028996-4120dfd0-fe13-4b2c-954e-ca53ae9fbbd0.png)
我不是很懂前端啊 可能是我弄的方法有问题

**Comment by Jimmylxue** [comment]
感谢反馈，确实有这个问题。
原因在于触发第二天定时任务时，时间当天的时间并未刷新，还是用的原来的时间，目前已经修复！
拉取最新master代码即可。
