### ISSUE TITLE
想问问大佬这个功能只能用测试号来进行吗？能否自己申请订阅号然后走模板消息？

### ISSUE THREAD

**Issue by dyx930916** [Jimmylxue/Vitality-reminder#2]
想问问大佬这个功能只能用测试号来进行吗？能否自己申请订阅号然后走模板消息？

**Comment by Jimmylxue** [comment]
自己申请订阅号也是可以的，但是wx的这个群发接口现在要求比较严格，必须是通过企业认证的订阅号才有接口请求的权限，而大多数开发者就最多到个人认证这一步，所以基本上是搞不了
...
之所以用测试号是因为测试号开放了近乎所有的接口权限
...
